-- Create table for application logs
CREATE TABLE app_logs (
    log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    log_level       VARCHAR2(20) NOT NULL,
    message         CLOB,
    error_stack     CLOB,
    created_on      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100) DEFAULT COALESCE(sys_context('APEX$SESSION','APP_USER'), USER)
);

-- Add comments
COMMENT ON TABLE app_logs IS 'Stores application log messages including errors and warnings';
COMMENT ON COLUMN app_logs.log_id IS 'Primary key';
COMMENT ON COLUMN app_logs.log_level IS 'Level of the log (INFO, WARNING, ERROR)';
COMMENT ON COLUMN app_logs.message IS 'Main log message';
COMMENT ON COLUMN app_logs.error_stack IS 'Stack trace or error details if applicable';
COMMENT ON COLUMN app_logs.created_on IS 'Timestamp when the log was created';
COMMENT ON COLUMN app_logs.created_by IS 'User who created the log (APEX user or DB user)';
