-- Script: create_surety_users_and_grants.sql
-- Purpose: Create SURETY and SURETY_LOGS users and configure cross-schema access.
-- Notes: In Oracle 19c, privileges on "ALL TABLES IN A SCHEMA" must be granted individually
--        or via a PL/SQL loop. There is no direct "GRANT SELECT ON SCHEMA X TO Y" command.

-- 1. Create the Owner/Log User (SURETY_LOGS)
-- This user will own the tables and procedures.
CREATE USER surety_logs IDENTIFIED BY "StrongPassLogs1!"
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO surety_logs;
GRANT CREATE TABLE TO surety_logs;
GRANT CREATE PROCEDURE TO surety_logs;
GRANT CREATE SEQUENCE TO surety_logs;
GRANT CREATE TRIGGER TO surety_logs;

-- 2. Create the Application User (SURETY)
-- This user connects and accesses SURETY_LOGS objects.
CREATE USER surety IDENTIFIED BY "StrongPassSurety1!"
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO surety;
GRANT CREATE SYNONYM TO surety; 
-- (Optional: Add create table/procedure if SURETY also owns objects)

-- 3. Procedure to Grant Privileges Dynamically
-- Since SURETY_LOGS is currently empty (newly created), we cannot grant specific table privileges yet.
-- This procedure, created in SURETY_LOGS schema, can be run whenever new tables are added
-- to refresh the grants for SURETY.

GRANT CREATE PROCEDURE TO surety_logs;

CONNECT surety_logs/"StrongPassLogs1!";

CREATE OR REPLACE PROCEDURE grant_access_to_surety IS
BEGIN
    -- 1. Grant INSERT and READ on all Tables
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'GRANT INSERT, READ ON ' || t.table_name || ' TO surety';
    END LOOP;

    -- 2. Grant EXECUTE on all Procedures/Functions/Packages
    FOR p IN (SELECT object_name, object_type FROM user_objects 
              WHERE object_type IN ('PROCEDURE', 'FUNCTION', 'PACKAGE')) LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON "' || p.object_name || '" TO surety';
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('Grants refreshed for user SURETY.');
END;
/
SHOW ERRORS;

-- 4. (Example Usage) Creating a dummy table to demonstrate the grant
-- Still connected as SURETY_LOGS
CREATE TABLE app_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    log_msg VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE PROCEDURE log_message(p_msg IN VARCHAR2) IS
BEGIN
    INSERT INTO app_log (log_msg) VALUES (p_msg);
    COMMIT;
END;
/

-- 5. Run the Grant Procedure
-- This applies the requested permissions to the newly created objects
BEGIN
    grant_access_to_surety;
END;
/

-- 6. Verification (Optional - Run as System or check manually)
-- SELECT * FROM dba_tab_privs WHERE grantee = 'SURETY' AND owner = 'SURETY_LOGS';
