-- Tables for Dynamic Authorization Scheme
-- Target: Oracle 19c+
-- Best Practices: Identity Columns, Constraints, Comments

-- 1. Roles Table
CREATE TABLE app_roles (
    role_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_key         VARCHAR2(50) NOT NULL,
    role_name        VARCHAR2(100) NOT NULL,
    description      VARCHAR2(500),
    is_active        VARCHAR2(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
    created_by       VARCHAR2(255) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by       VARCHAR2(255),
    updated_on       TIMESTAMP,
    CONSTRAINT pk_app_roles PRIMARY KEY (role_id),
    CONSTRAINT uk_app_roles_key UNIQUE (role_key)
);

COMMENT ON TABLE app_roles IS 'Stores application roles (e.g., ADMIN, MANAGER, USER).';

-- 2. Permissions Table (Granular control for Pages, Regions, Buttons)
CREATE TABLE app_permissions (
    permission_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    permission_code  VARCHAR2(100) NOT NULL, -- e.g., 'PAGE_1_VIEW', 'BTN_DELETE_EXECUTE'
    description      VARCHAR2(500),
    component_type   VARCHAR2(50), -- Optional: PAGE, REGION, BUTTON, MENU
    created_by       VARCHAR2(255) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_permissions PRIMARY KEY (permission_id),
    CONSTRAINT uk_app_perm_code UNIQUE (permission_code)
);

COMMENT ON TABLE app_permissions IS 'Stores specific permissions identified by a unique code.';

-- 3. Role-Permission Mapping
CREATE TABLE app_role_permissions (
    role_id          NUMBER NOT NULL,
    permission_id    NUMBER NOT NULL,
    created_by       VARCHAR2(255) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_role_perm PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES app_roles(role_id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES app_permissions(permission_id) ON DELETE CASCADE
);

COMMENT ON TABLE app_role_permissions IS 'Maps permissions to roles (Many-to-Many).';

-- 4. User-Role Mapping
CREATE TABLE app_user_roles (
    user_role_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_name        VARCHAR2(255) NOT NULL, -- references APEX APP_USER
    role_id          NUMBER NOT NULL,
    created_by       VARCHAR2(255) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    created_on       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_user_roles PRIMARY KEY (user_role_id),
    CONSTRAINT uk_app_user_role UNIQUE (user_name, role_id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES app_roles(role_id) ON DELETE CASCADE
);

COMMENT ON TABLE app_user_roles IS 'Assigns roles to Users.';

-- Indexes for performance
CREATE INDEX idx_ur_username ON app_user_roles(user_name);
CREATE INDEX idx_rp_role ON app_role_permissions(role_id);
CREATE INDEX idx_rp_perm ON app_role_permissions(permission_id);

-- Sample Data (Optional, for testing)
-- INSERT INTO app_roles (role_key, role_name) VALUES ('ADMIN', 'Administrator');
-- INSERT INTO app_permissions (permission_code, description) VALUES ('PAGE:1:ACCESS', 'Access to Home Page');
-- ...
