/*
================================================================================
  Dynamic Authorization Scheme for Oracle APEX
  
  Source: Louis Moreaux - https://lmoreaux.hashnode.dev/
  Article: "How to implement a dynamic authorization scheme in Oracle APEX"
  
  This implementation allows dynamic management of user permissions for
  APEX components (Pages, Regions, Buttons, Page Items, Menus) without
  modifying application code.
  
  Features:
  - Auto-registers components when accessed for the first time
  - Works with APEX built-in ACL roles (reader, contributor, administrator)
  - Supports all major component types
  - Uses autonomous transaction for component registration
  
  Oracle APEX Version: 19c+
================================================================================
*/

--------------------------------------------------------------------------------
-- STEP 1: Create the Data Model
--------------------------------------------------------------------------------

-- Table to store APEX components that will use dynamic authorization
CREATE TABLE apex_auth_component (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
                        CONSTRAINT apex_auth_componen_id_pk PRIMARY KEY,
    app_id              NUMBER NOT NULL,
    page_id             NUMBER NOT NULL,
    component_static_id VARCHAR2(255 CHAR),
    component_type      VARCHAR2(255 CHAR) NOT NULL
);

-- Add comment for documentation
COMMENT ON TABLE apex_auth_component IS 'Stores APEX components for dynamic authorization scheme';
COMMENT ON COLUMN apex_auth_component.app_id IS 'APEX Application ID';
COMMENT ON COLUMN apex_auth_component.page_id IS 'APEX Page ID';
COMMENT ON COLUMN apex_auth_component.component_static_id IS 'Static ID of the component (null for pages)';
COMMENT ON COLUMN apex_auth_component.component_type IS 'Component type from APEX metadata views';

-- Table to store role-to-component authorization mappings
CREATE TABLE apex_auth_role_component (
    id                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
                           CONSTRAINT apex_auth_role_com_id_pk PRIMARY KEY,
    apex_auth_component_id NUMBER
                           CONSTRAINT apex_auth_rol_apex_auth_com_fk
                           REFERENCES apex_auth_component ON DELETE CASCADE,
    role_static_id         VARCHAR2(255 CHAR) NOT NULL,
    is_authorized          VARCHAR2(1 CHAR) DEFAULT 'N' 
                           CONSTRAINT apex_auth_role_is_authoriz_ck
                           CHECK (is_authorized IN ('Y','N'))
);

-- Add comment for documentation
COMMENT ON TABLE apex_auth_role_component IS 'Maps roles to components with authorization flag';
COMMENT ON COLUMN apex_auth_role_component.role_static_id IS 'Role identifier (e.g., READER, CONTRIBUTOR, ADMINISTRATOR)';
COMMENT ON COLUMN apex_auth_role_component.is_authorized IS 'Y=Authorized, N=Not Authorized';

-- Create index for better performance on foreign key lookups
CREATE INDEX apex_auth_role_com_i1 ON apex_auth_role_component (apex_auth_component_id);

-- Create unique constraint to prevent duplicate component entries
CREATE UNIQUE INDEX apex_auth_comp_uk ON apex_auth_component (
    app_id, 
    page_id, 
    component_type, 
    NVL(component_static_id, '~NULL~')
);


--------------------------------------------------------------------------------
-- STEP 2: Create the PL/SQL Package Specification
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE dynamic_authorization AS
    /*
    ================================================================================
      Dynamic Authorization Package
      
      Purpose: Provides functions to check if a user is authorized to access
               an APEX component based on their assigned roles.
               
      Usage: Call is_component_authorized from an Authorization Scheme
             with Evaluation Point set to "Once per component" or 
             "Always (No Caching)"
    ================================================================================
    */
    
    -- Main function to check if user can access a component
    FUNCTION is_component_authorized (
        p_application_id IN NUMBER,
        p_page_id        IN NUMBER,
        p_component_type IN VARCHAR2,
        p_component_id   IN NUMBER,
        p_component_name IN VARCHAR2
    ) RETURN BOOLEAN;
    
END dynamic_authorization;
/


--------------------------------------------------------------------------------
-- STEP 3: Create the PL/SQL Package Body
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY dynamic_authorization AS

    /*
    ============================================================================
      PRIVATE PROCEDURE: register_component
      
      Purpose: Inserts a new component into the apex_auth_component table
               when it's accessed for the first time with this authorization.
               
      Notes: 
        - Uses PRAGMA AUTONOMOUS_TRANSACTION to commit independently
        - This allows registration even if the main transaction rolls back
        - Silently handles duplicates with exception handler
    ============================================================================
    */
    PROCEDURE register_component(
        p_application_id      IN NUMBER,
        p_page_id             IN NUMBER,
        p_component_type      IN VARCHAR2,
        p_component_static_id IN VARCHAR2
    )
    IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO apex_auth_component
            (app_id, page_id, component_type, component_static_id)
        VALUES
            (p_application_id, p_page_id, p_component_type, p_component_static_id);
        COMMIT;
        
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            -- Component already registered, ignore
            NULL;
        WHEN OTHERS THEN
            -- Log error but don't fail the authorization check
            apex_debug.error(
                p_message => 'Error registering component: %s',
                p0        => SQLERRM
            );
    END register_component;


    /*
    ============================================================================
      PUBLIC FUNCTION: is_component_authorized
      
      Purpose: Checks if the current user has authorization to access
               the specified APEX component.
               
      Parameters:
        p_application_id - The APEX application ID (:APP_ID)
        p_page_id        - The page ID (:APP_PAGE_ID)
        p_component_type - The component type (:APP_COMPONENT_TYPE)
                           Values: APEX_APPLICATION_PAGES
                                   APEX_APPLICATION_PAGE_REGIONS
                                   APEX_APPLICATION_BUTTONS (for buttons)
                                   APEX_APPLICATION_PAGE_ITEMS
                                   APEX_APPLICATION_LIST_ENTRIES (for menus)
        p_component_id   - The internal component ID (:APP_COMPONENT_ID)
        p_component_name - The component name (:APP_COMPONENT_NAME)
        
      Returns: TRUE if authorized, FALSE otherwise
      
      Logic:
        1. Determine the component's static_id based on component type
        2. Check if component is registered; if not, register it
        3. Check if user's role(s) have authorization for this component
    ============================================================================
    */
    FUNCTION is_component_authorized (
        p_application_id IN NUMBER,
        p_page_id        IN NUMBER,
        p_component_type IN VARCHAR2,
        p_component_id   IN NUMBER,
        p_component_name IN VARCHAR2
    ) 
    RETURN BOOLEAN
    IS
        l_is_authorized        BOOLEAN := FALSE;
        l_component_static_id  apex_auth_component.component_static_id%TYPE;
        l_component_registered PLS_INTEGER;
        l_component_authorized PLS_INTEGER;
    BEGIN
        -- Debug logging for troubleshooting
        apex_debug.enter(
            p_routine_name => 'dynamic_authorization.is_component_authorized', 
            p_name01       => 'p_application_id',
            p_value01      => p_application_id,
            p_name02       => 'p_page_id',
            p_value02      => p_page_id,
            p_name03       => 'p_component_type',
            p_value03      => p_component_type,
            p_name04       => 'p_component_id',
            p_value04      => p_component_id,
            p_name05       => 'p_component_name',
            p_value05      => p_component_name
        );
        
        /*
        --------------------------------------------------------------------
          Get the static_id for the component based on its type
          Each component type has a different APEX metadata view
        --------------------------------------------------------------------
        */
        CASE p_component_type
            -- Pages don't have a static_id, use NULL
            WHEN 'APEX_APPLICATION_PAGES' THEN
                l_component_static_id := NULL;
                
            -- Regions - get static_id from apex_application_page_regions
            WHEN 'APEX_APPLICATION_PAGE_REGIONS' THEN
                SELECT static_id
                  INTO l_component_static_id
                  FROM apex_application_page_regions
                 WHERE application_id = p_application_id
                   AND page_id = p_page_id
                   AND region_id = p_component_id;
                   
            -- Buttons - get button_static_id from apex_application_page_buttons
            WHEN 'APEX_APPLICATION_BUTTONS' THEN
                SELECT button_static_id
                  INTO l_component_static_id
                  FROM apex_application_page_buttons
                 WHERE application_id = p_application_id
                   AND page_id = p_page_id
                   AND button_id = p_component_id;
                   
            -- Page Items - get item_name as static_id from apex_application_page_items
            WHEN 'APEX_APPLICATION_PAGE_ITEMS' THEN
                SELECT item_name
                  INTO l_component_static_id
                  FROM apex_application_page_items
                 WHERE application_id = p_application_id
                   AND page_id = p_page_id
                   AND item_id = p_component_id;
                   
            -- List Entries (Navigation Menu items) - use entry_text as identifier
            WHEN 'APEX_APPLICATION_LIST_ENTRIES' THEN
                SELECT entry_text
                  INTO l_component_static_id
                  FROM apex_application_list_entries
                 WHERE application_id = p_application_id
                   AND list_entry_id = p_component_id;
                   
            -- Handle any other/unknown component types
            ELSE
                l_component_static_id := p_component_name;
                apex_debug.warn(
                    p_message => 'Unknown component type: %s. Using component_name as static_id.',
                    p0        => p_component_type
                );
        END CASE;
        
        apex_debug.info(
            p_message => 'Component static_id resolved to: %s',
            p0        => NVL(l_component_static_id, '(NULL - Page)')
        );

        /*
        --------------------------------------------------------------------
          Check if component is already registered in our table
        --------------------------------------------------------------------
        */
        SELECT COUNT(*)
          INTO l_component_registered
          FROM apex_auth_component
         WHERE app_id = p_application_id
           AND page_id = p_page_id
           AND component_type = p_component_type
           AND (   (l_component_static_id IS NULL AND component_static_id IS NULL)
                OR component_static_id = l_component_static_id);

        /*
        --------------------------------------------------------------------
          If not registered, register it now (auto-registration feature)
        --------------------------------------------------------------------
        */
        IF l_component_registered = 0 THEN
            apex_debug.info(
                p_message => 'Component not registered. Auto-registering...'
            );
            register_component(
                p_application_id      => p_application_id,
                p_page_id             => p_page_id,
                p_component_type      => p_component_type,
                p_component_static_id => l_component_static_id
            );
        END IF;

        /*
        --------------------------------------------------------------------
          Check if user has authorization for this component
          
          This query:
          1. Joins to APEX ACL to get user's roles
          2. Joins to our role-component mapping table
          3. Joins to our component table
          4. Checks if is_authorized = 'Y' for any of user's roles
        --------------------------------------------------------------------
        */
        SELECT COUNT(*)
          INTO l_component_authorized
          FROM apex_appl_acl_user_roles aaur
          JOIN apex_auth_role_component aurc 
            ON aurc.role_static_id = aaur.role_static_id
           AND aurc.is_authorized = 'Y'
          JOIN apex_auth_component auco 
            ON auco.id = aurc.apex_auth_component_id
           AND auco.app_id = p_application_id
           AND auco.page_id = p_page_id
           AND auco.component_type = p_component_type
           AND (   l_component_static_id IS NULL 
                OR auco.component_static_id = l_component_static_id)
         WHERE aaur.application_id = p_application_id
           AND aaur.user_name = SYS_CONTEXT('APEX$SESSION', 'APP_USER');

        l_is_authorized := (l_component_authorized > 0);
        
        apex_debug.info(
            p_message => 'Authorization result: %s (found %s matching role grants)',
            p0        => CASE WHEN l_is_authorized THEN 'AUTHORIZED' ELSE 'DENIED' END,
            p1        => l_component_authorized
        );

        RETURN l_is_authorized;
        
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Component metadata not found - deny access
            apex_debug.error(
                p_message => 'Component not found in APEX metadata. Denying access.'
            );
            RETURN FALSE;
            
        WHEN OTHERS THEN
            -- Log error and deny access
            apex_debug.error(
                p_message => 'Error in is_component_authorized: %s',
                p0        => SQLERRM
            );
            RETURN FALSE;
            
    END is_component_authorized;

END dynamic_authorization;
/


--------------------------------------------------------------------------------
-- STEP 4: Verification - Check objects were created successfully
--------------------------------------------------------------------------------

-- Verify tables exist
SELECT table_name 
  FROM user_tables 
 WHERE table_name IN ('APEX_AUTH_COMPONENT', 'APEX_AUTH_ROLE_COMPONENT');

-- Verify package is valid
SELECT object_name, object_type, status 
  FROM user_objects 
 WHERE object_name = 'DYNAMIC_AUTHORIZATION';

--------------------------------------------------------------------------------
-- STEP 5: Instructions for APEX Application Setup
--------------------------------------------------------------------------------

/*
================================================================================
  APEX APPLICATION SETUP INSTRUCTIONS
================================================================================

1. CREATE THE AUTHORIZATION SCHEME:
   --------------------------------
   a. In APEX Builder, go to: Shared Components > Authorization Schemes
   b. Click "Create"
   c. Set the following:
      - Name: Dynamic Authorization
      - Scheme Type: PL/SQL Function Returning Boolean
      - PL/SQL Function Body (copy the code below):

return 
dynamic_authorization.is_component_authorized(
  p_application_id => :APP_ID,
  p_page_id        => :APP_PAGE_ID,
  p_component_type => :APP_COMPONENT_TYPE,
  p_component_id   => :APP_COMPONENT_ID,
  p_component_name => :APP_COMPONENT_NAME
);

      - Evaluation Point: "Once per component" (recommended for production)
                          OR "Always (No Caching)" (for real-time changes)
      
      NOTE: The special bind variables :APP_COMPONENT_TYPE, :APP_COMPONENT_ID,
            and :APP_COMPONENT_NAME are ONLY available when Evaluation Point
            is set to "Once per component" or "Always (No Caching)"


2. ASSIGN TO COMPONENTS:
   ----------------------
   For each component (Page, Region, Button, Item, Menu) you want to control:
   a. Select the component in Page Designer
   b. In the Property Editor, find "Security" section
   c. Set "Authorization Scheme" to "Dynamic Authorization"
   

3. CREATE ADMINISTRATION PAGE (Optional but recommended):
   -------------------------------------------------------
   Create a page with two Interactive Grids to manage authorizations:
   
   Master IG Query (Components):
   
   SELECT id,
          app_id,
          page_id,
          component_type,
          component_static_id
     FROM apex_auth_component
    WHERE app_id = :APP_ID
    ORDER BY page_id, component_type, component_static_id

   Detail IG Query (Role Authorizations):
   
   SELECT id,
          apex_auth_component_id,
          role_static_id,
          is_authorized
     FROM apex_auth_role_component
    WHERE apex_auth_component_id = :P_COMPONENT_ID


4. SEED ROLE DATA (Example for default APEX ACL roles):
   -----------------------------------------------------
   After components are registered, you need to create role mappings.
   Example to seed all roles for a newly registered component:
*/

-- Example: Insert role mappings for all components (run after components are registered)
INSERT INTO apex_auth_role_component (apex_auth_component_id, role_static_id, is_authorized)
SELECT c.id, r.role_static_id, 'N'
  FROM apex_auth_component c
 CROSS JOIN (
    SELECT 'READER' AS role_static_id FROM dual
    UNION ALL
    SELECT 'CONTRIBUTOR' FROM dual
    UNION ALL
    SELECT 'ADMINISTRATOR' FROM dual
 ) r
 WHERE NOT EXISTS (
    SELECT 1 
      FROM apex_auth_role_component rc 
     WHERE rc.apex_auth_component_id = c.id 
       AND rc.role_static_id = r.role_static_id
 );

COMMIT;

/*
================================================================================
  COMPONENT TYPES REFERENCE
================================================================================

When the authorization scheme is evaluated, APEX passes the following 
component types via :APP_COMPONENT_TYPE:

  Component Type                      | Description
  ------------------------------------|------------------------------------------
  APEX_APPLICATION_PAGES              | Page-level authorization
  APEX_APPLICATION_PAGE_REGIONS       | Regions (Classic Report, IR, IG, etc.)
  APEX_APPLICATION_BUTTONS            | Buttons
  APEX_APPLICATION_PAGE_ITEMS         | Page Items (text fields, select lists)
  APEX_APPLICATION_LIST_ENTRIES       | Navigation menu entries
  APEX_APPLICATION_PAGE_PROC          | Page processes
  APEX_APPLICATION_PAGE_COMP_SET      | Component settings
  APEX_APPLICATION_PAGE_BRANCHES      | Branches

================================================================================
*/


--------------------------------------------------------------------------------
-- STEP 6: Sample Data for Testing (Optional)
--------------------------------------------------------------------------------

/*
-- Insert test authorization for a page (example: Page 1 accessible by ADMINISTRATOR)
INSERT INTO apex_auth_component (app_id, page_id, component_type, component_static_id)
VALUES (100, 1, 'APEX_APPLICATION_PAGES', NULL);

-- Get the component ID
-- Then insert role authorization
INSERT INTO apex_auth_role_component (apex_auth_component_id, role_static_id, is_authorized)
VALUES (1, 'ADMINISTRATOR', 'Y');

INSERT INTO apex_auth_role_component (apex_auth_component_id, role_static_id, is_authorized)
VALUES (1, 'CONTRIBUTOR', 'N');

INSERT INTO apex_auth_role_component (apex_auth_component_id, role_static_id, is_authorized)
VALUES (1, 'READER', 'N');

COMMIT;
*/


--------------------------------------------------------------------------------
-- STEP 7: Useful Queries for Administration
--------------------------------------------------------------------------------

-- View all registered components with their authorizations
SELECT c.app_id,
       c.page_id,
       c.component_type,
       c.component_static_id,
       rc.role_static_id,
       rc.is_authorized
  FROM apex_auth_component c
  LEFT JOIN apex_auth_role_component rc ON rc.apex_auth_component_id = c.id
 ORDER BY c.app_id, c.page_id, c.component_type, rc.role_static_id;

-- View user's effective permissions
SELECT c.page_id,
       c.component_type,
       c.component_static_id,
       aaur.user_name,
       aaur.role_static_id,
       rc.is_authorized
  FROM apex_auth_component c
  JOIN apex_auth_role_component rc ON rc.apex_auth_component_id = c.id
  JOIN apex_appl_acl_user_roles aaur ON aaur.role_static_id = rc.role_static_id
                                    AND aaur.application_id = c.app_id
 WHERE c.app_id = :APP_ID
   AND rc.is_authorized = 'Y'
 ORDER BY aaur.user_name, c.page_id;


/*
================================================================================
  END OF SCRIPT
================================================================================
*/
