--------------------------------------------------------------------------------
-- Dynamic Authorization Scheme for Oracle APEX
-- 
-- Overview:
-- This script sets up a "Dynamic Authorization Scheme" that allows you to manage
-- permissions for APEX components (Pages, Regions, Buttons, Items, Menus)
-- via a configuration table (AUTH_COMPONENT_CONFIG) rather than creating
-- separate Authorization Schemes for every role or permission.
--------------------------------------------------------------------------------

-- =============================================================================
-- 1. DATABASE OBJECTS (DDL)
-- =============================================================================

-- 1.1. Roles Table
CREATE TABLE auth_roles (
    role_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(4000)
);

-- 1.2. User Roles Mapping
CREATE TABLE auth_user_roles (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(255) NOT NULL,
    role_id     NUMBER NOT NULL,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES auth_roles(role_id),
    CONSTRAINT uq_user_role UNIQUE (username, role_id)
);

-- 1.3. Component Authorization Configuration
-- Maps specific APEX components to required roles.
-- The lookup key is (APP_ID, PAGE_ID, COMPONENT_NAME).
CREATE TABLE auth_component_config (
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    app_id          NUMBER NOT NULL,
    page_id         NUMBER, -- NULL for global components
    component_name  VARCHAR2(255), -- The Static ID or Name of the component
    component_type  VARCHAR2(50),  -- e.g., 'PAGE', 'REGION', 'BUTTON', 'ITEM'
    required_role   VARCHAR2(100), -- The role required
    is_active       VARCHAR2(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uq_comp_config UNIQUE (app_id, page_id, component_name)
);

CREATE INDEX idx_auth_config_lookup ON auth_component_config (app_id, page_id, component_name);

-- =============================================================================
-- 2. PL/SQL PACKAGE
-- =============================================================================
CREATE OR REPLACE PACKAGE pkg_dynamic_auth AS
    
    -- Main function to be called by the APEX Authorization Scheme
    -- Returns TRUE if the current user is authorized for the current component.
    FUNCTION is_authorized (
        p_component_name IN VARCHAR2 DEFAULT NULL
    ) RETURN BOOLEAN;

    -- Helper to check if a user has a specific role
    FUNCTION user_has_role (
        p_username  IN VARCHAR2,
        p_role_name IN VARCHAR2
    ) RETURN BOOLEAN;

END pkg_dynamic_auth;
/

CREATE OR REPLACE PACKAGE BODY pkg_dynamic_auth AS

    FUNCTION user_has_role (
        p_username  IN VARCHAR2,
        p_role_name IN VARCHAR2
    ) RETURN BOOLEAN IS
        l_count NUMBER;
    BEGIN
        -- Bypass for null role (public)
        IF p_role_name IS NULL THEN
            RETURN TRUE;
        END IF;

        -- Example logic: Check DB table. 
        -- Can be replaced with APEX_ACL calls or LDAP groups.
        SELECT COUNT(*)
        INTO l_count
        FROM auth_user_roles ur
        JOIN auth_roles r ON ur.role_id = r.role_id
        WHERE UPPER(ur.username) = UPPER(p_username)
          AND UPPER(r.role_name) = UPPER(p_role_name);

        RETURN l_count > 0;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
    END user_has_role;

    FUNCTION is_authorized (
        p_component_name IN VARCHAR2 DEFAULT NULL
    ) RETURN BOOLEAN IS
        l_app_id         NUMBER := v('APP_ID');
        l_page_id        NUMBER := v('APP_PAGE_ID');
        l_component_name VARCHAR2(255);
        l_required_role  VARCHAR2(100);
        l_user           VARCHAR2(255) := v('APP_USER');
    BEGIN
        -- 1. Determine Component Name
        IF p_component_name IS NOT NULL THEN
            l_component_name := p_component_name;
        ELSE
            -- Attempt to get component name from APEX Global Context
            -- This works for Regions, Buttons, Items in most rendering phases.
            l_component_name := apex_application.g_component_name;
            
            -- Fallback: If no component name is found, and we are likely checking 
            -- the Page itself (Authorization Scheme on Page Attributes), use Page ID.
            IF l_component_name IS NULL THEN
                 l_component_name := TO_CHAR(l_page_id);
            END IF;
        END IF;

        -- 2. Lookup configuration
        -- We return TRUE (Allow) if no record is found (Fail Open). 
        -- Change to FALSE if you want "Deny by Default".
        BEGIN
            SELECT required_role
            INTO l_required_role
            FROM auth_component_config
            WHERE app_id = l_app_id
              AND (page_id = l_page_id OR page_id IS NULL)
              AND UPPER(component_name) = UPPER(l_component_name)
              AND is_active = 'Y';
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                -- No specific restriction found for this component.
                -- Check if there is a 'GLOBAL' restriction? 
                -- For now, return TRUE.
                RETURN TRUE;
            WHEN TOO_MANY_ROWS THEN
                -- Configuration ambiguity, deny access.
                apex_debug.error('Dynamic Auth: Multiple config rows found for ' || l_component_name);
                RETURN FALSE;
        END;

        -- 3. Validate Role
        IF l_required_role IS NULL THEN
            RETURN TRUE;
        END IF;

        RETURN user_has_role(l_user, l_required_role);

    EXCEPTION
        WHEN OTHERS THEN
            apex_debug.error('Dynamic Auth Exception: ' || SQLERRM);
            RETURN FALSE;
    END is_authorized;

END pkg_dynamic_auth;
/

-- =============================================================================
-- 3. SETUP INSTRUCTIONS & SAMPLE DATA
-- =============================================================================

/*
STEP 1: Run the DDL and Package creation above.

STEP 2: Insert Sample Data
*/

-- Create Roles
INSERT INTO auth_roles (role_name, description) VALUES ('ADMIN', 'System Administrator');
INSERT INTO auth_roles (role_name, description) VALUES ('MANAGER', 'Manager');

-- Assign Role to User (Replace 'YOUR_USER' with your APEX username)
INSERT INTO auth_user_roles (username, role_id) 
  SELECT 'ADMIN_USER', role_id FROM auth_roles WHERE role_name = 'ADMIN';

-- Configure Permissions
-- Example 1: Secure Page 10 (Home) - Only ADMIN can see it
-- For Pages, the component_name defaults to the Page ID (e.g., '10') if not provided.
-- INSERT INTO auth_component_config (app_id, page_id, component_name, component_type, required_role)
-- VALUES (100, 10, '10', 'PAGE', 'ADMIN');

-- Example 2: Secure a Button with Static ID 'BTN_SAVE' on Page 10
-- INSERT INTO auth_component_config (app_id, page_id, component_name, component_type, required_role)
-- VALUES (100, 10, 'BTN_SAVE', 'BUTTON', 'MANAGER');

/*
STEP 3: Configure APEX Application

1. Go to Shared Components > Security > Authorization Schemes.
2. Click "Create" > "From Scratch".
3. Settings:
   - Name: Dynamic_Component_Auth
   - Scheme Type: PL/SQL Function Returning Boolean
   - PL/SQL Function Body:
     return pkg_dynamic_auth.is_authorized;
   - Validate authorization scheme: Once per component (NOT Once per session)
   - Error Message: You do not have permission to access this component.

4. Apply the Scheme:
   - To a Page: Edit Page Attributes > Security > Authorization Scheme > Select "Dynamic_Component_Auth".
   - To a Region/Button/Item: Edit Component > Security > Authorization Scheme > Select "Dynamic_Component_Auth".
   IMPORTANT: Ensure the component has a "Static ID" matching what you put in AUTH_COMPONENT_CONFIG.COMPONENT_NAME.
   (For Pages, it uses the Page ID string).
*/

COMMIT;
