#!/bin/bash
#===============================================================================
# Script: 04_mw_install_tomcat.sh
# Server: EC2 (Middleware Server - 80.238.234.247)
# OS: Ubuntu 24.04
# OS User: root
# Description: Install Apache Tomcat 10.1 and deploy ORDS
#===============================================================================
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

#===============================================================================
# Configuration
#===============================================================================
TOMCAT_VERSION="10.1.34"
TOMCAT_MAJOR="10"
TOMCAT_USER="tomcat"
TOMCAT_HOME="/opt/tomcat"
TOMCAT_DOWNLOAD_URL="https://dlcdn.apache.org/tomcat/tomcat-${TOMCAT_MAJOR}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"

ORDS_USER="ords"
ORDS_HOME="/opt/ords"
ORDS_CONFIG="/opt/ords/config"
ORDS_VERSION="24.3"

JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"

#===============================================================================
# Pre-flight Checks
#===============================================================================

log_info "============================================================"
log_info "Apache Tomcat ${TOMCAT_VERSION} Installation Script"
log_info "============================================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root or with sudo"
    exit 1
fi

# Check Java
if [ ! -d "${JAVA_HOME}" ]; then
    log_error "JAVA_HOME not found: ${JAVA_HOME}"
    log_error "Please run 02_mw_install_prereqs.sh first"
    exit 1
fi

# Check ORDS is installed
if [ ! -f "${ORDS_HOME}/ords-${ORDS_VERSION}/bin/ords" ]; then
    log_error "ORDS not found. Please run 03_mw_install_ords.sh first"
    exit 1
fi

# Check ORDS is configured
if [ ! -d "${ORDS_CONFIG}/databases" ]; then
    log_warn "ORDS configuration not found at ${ORDS_CONFIG}/databases"
    log_warn "Make sure ORDS install command was run successfully"
    log_warn "Continuing anyway - you can configure ORDS later"
fi

#===============================================================================
# Installation
#===============================================================================

log_step "Step 1: Download Tomcat ${TOMCAT_VERSION}"
cd /tmp

if [ -f "apache-tomcat-${TOMCAT_VERSION}.tar.gz" ]; then
    log_warn "Tomcat archive already exists. Skipping download..."
else
    wget -q --show-progress "${TOMCAT_DOWNLOAD_URL}"
    log_info "Downloaded Tomcat ${TOMCAT_VERSION}"
fi

log_step "Step 2: Extract Tomcat to ${TOMCAT_HOME}"
# Backup existing if present
if [ -d "${TOMCAT_HOME}/bin" ]; then
    log_warn "Existing Tomcat installation found. Backing up..."
    mv ${TOMCAT_HOME} ${TOMCAT_HOME}.backup.$(date +%Y%m%d%H%M%S)
fi

mkdir -p ${TOMCAT_HOME}
tar xzf apache-tomcat-${TOMCAT_VERSION}.tar.gz -C ${TOMCAT_HOME} --strip-components=1
log_info "Tomcat extracted to ${TOMCAT_HOME}"

log_step "Step 3: Set ownership and permissions"
chown -R ${TOMCAT_USER}:${TOMCAT_USER} ${TOMCAT_HOME}
chmod +x ${TOMCAT_HOME}/bin/*.sh

log_step "Step 4: Create setenv.sh for Tomcat"
cat > ${TOMCAT_HOME}/bin/setenv.sh << EOF
#!/bin/bash
#===============================================================================
# Tomcat Environment Configuration
# Generated by 04_mw_install_tomcat.sh
#===============================================================================

export JAVA_HOME="${JAVA_HOME}"
export CATALINA_HOME="${TOMCAT_HOME}"
export CATALINA_BASE="${TOMCAT_HOME}"
export CATALINA_PID="${TOMCAT_HOME}/temp/tomcat.pid"

# JVM Memory Settings (adjust based on your server RAM)
export CATALINA_OPTS="-Xms512m -Xmx2048m -server -XX:+UseG1GC"

# ORDS Configuration
export JAVA_OPTS="-Djava.awt.headless=true -Dconfig.url=${ORDS_CONFIG}"

# Optional: Enable JMX monitoring (uncomment if needed)
# export CATALINA_OPTS="\${CATALINA_OPTS} -Dcom.sun.management.jmxremote"
# export CATALINA_OPTS="\${CATALINA_OPTS} -Dcom.sun.management.jmxremote.port=9090"
# export CATALINA_OPTS="\${CATALINA_OPTS} -Dcom.sun.management.jmxremote.ssl=false"
# export CATALINA_OPTS="\${CATALINA_OPTS} -Dcom.sun.management.jmxremote.authenticate=false"
EOF
chmod +x ${TOMCAT_HOME}/bin/setenv.sh
chown ${TOMCAT_USER}:${TOMCAT_USER} ${TOMCAT_HOME}/bin/setenv.sh
log_info "Created setenv.sh"

log_step "Step 5: Generate ORDS WAR file"
if [ -f "${ORDS_HOME}/ords.war" ]; then
    log_warn "ORDS WAR already exists. Recreating..."
    rm -f ${ORDS_HOME}/ords.war
fi

sudo -u ${ORDS_USER} ${ORDS_HOME}/ords-${ORDS_VERSION}/bin/ords war ${ORDS_HOME}/ords.war
log_info "ORDS WAR file created at ${ORDS_HOME}/ords.war"

log_step "Step 6: Deploy ORDS WAR to Tomcat"
cp ${ORDS_HOME}/ords.war ${TOMCAT_HOME}/webapps/ords.war
chown ${TOMCAT_USER}:${TOMCAT_USER} ${TOMCAT_HOME}/webapps/ords.war
log_info "ORDS WAR deployed to Tomcat webapps"

log_step "Step 7: Create ORDS context configuration"
mkdir -p ${TOMCAT_HOME}/conf/Catalina/localhost
cat > ${TOMCAT_HOME}/conf/Catalina/localhost/ords.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ORDS Context Configuration
  Generated by 04_mw_install_tomcat.sh
-->
<Context docBase="${TOMCAT_HOME}/webapps/ords" path="/ords" reloadable="false">
    <Parameter name="config.url" value="${ORDS_CONFIG}" override="false"/>
</Context>
EOF
chown ${TOMCAT_USER}:${TOMCAT_USER} ${TOMCAT_HOME}/conf/Catalina/localhost/ords.xml
log_info "Created ORDS context configuration"

log_step "Step 8: Configure APEX static files"
# Create symbolic link for APEX images
if [ -d "${ORDS_HOME}/doc_root/i" ]; then
    if [ -L "${TOMCAT_HOME}/webapps/i" ]; then
        rm -f ${TOMCAT_HOME}/webapps/i
    fi
    ln -s ${ORDS_HOME}/doc_root/i ${TOMCAT_HOME}/webapps/i
    log_info "Created symbolic link for APEX images"
else
    log_warn "APEX images directory not found at ${ORDS_HOME}/doc_root/i"
    log_warn "You need to copy APEX images manually:"
    log_warn "  1. Download APEX from Oracle"
    log_warn "  2. Extract and copy images folder to ${ORDS_HOME}/doc_root/i"
    mkdir -p ${ORDS_HOME}/doc_root/i
    chown -R ${ORDS_USER}:${ORDS_USER} ${ORDS_HOME}/doc_root
fi

log_step "Step 9: Create systemd service"
cat > /etc/systemd/system/tomcat.service << EOF
[Unit]
Description=Apache Tomcat ${TOMCAT_VERSION} Web Application Server
Documentation=https://tomcat.apache.org/
After=network.target

[Service]
Type=forking

User=${TOMCAT_USER}
Group=${TOMCAT_USER}

Environment="JAVA_HOME=${JAVA_HOME}"
Environment="CATALINA_PID=${TOMCAT_HOME}/temp/tomcat.pid"
Environment="CATALINA_HOME=${TOMCAT_HOME}"
Environment="CATALINA_BASE=${TOMCAT_HOME}"
Environment="CATALINA_OPTS=-Xms512M -Xmx2048M -server -XX:+UseG1GC"
Environment="JAVA_OPTS=-Djava.awt.headless=true -Dconfig.url=${ORDS_CONFIG}"

ExecStart=${TOMCAT_HOME}/bin/startup.sh
ExecStop=${TOMCAT_HOME}/bin/shutdown.sh

RestartSec=10
Restart=always

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ReadWritePaths=${TOMCAT_HOME}
ReadWritePaths=${ORDS_HOME}/config
ReadWritePaths=${ORDS_HOME}/logs

[Install]
WantedBy=multi-user.target
EOF
log_info "Created systemd service file"

log_step "Step 10: Reload systemd and enable Tomcat"
systemctl daemon-reload
systemctl enable tomcat
log_info "Tomcat service enabled"

log_step "Step 11: Start Tomcat"
systemctl start tomcat
sleep 5

# Check if Tomcat started successfully
if systemctl is-active --quiet tomcat; then
    log_info "Tomcat started successfully!"
else
    log_error "Tomcat failed to start. Check logs:"
    log_error "  journalctl -u tomcat -f"
    log_error "  tail -100 ${TOMCAT_HOME}/logs/catalina.out"
    exit 1
fi

log_step "Step 12: Verify installation"
echo ""
log_info "============================================================"
log_info "Tomcat Installation Complete!"
log_info "============================================================"
echo ""
echo "Tomcat Version:"
${TOMCAT_HOME}/bin/version.sh | grep "Server version"
echo ""
echo "Service Status:"
systemctl status tomcat --no-pager | head -10
echo ""
echo "Listening Ports:"
netstat -tlnp | grep -E '8080|8443' || ss -tlnp | grep -E '8080|8443'
echo ""
log_info "============================================================"
log_info "Access URLs"
log_info "============================================================"
log_info "ORDS:    http://80.238.234.247:8080/ords/"
log_info "APEX:    http://80.238.234.247:8080/ords/apex"
log_info "SQL Dev: http://80.238.234.247:8080/ords/sql-developer"
log_info "============================================================"
echo ""
log_info "Useful Commands:"
log_info "  View logs:      tail -f ${TOMCAT_HOME}/logs/catalina.out"
log_info "  Restart:        systemctl restart tomcat"
log_info "  Stop:           systemctl stop tomcat"
log_info "  Status:         systemctl status tomcat"
log_info "============================================================"
echo ""
log_warn "IMPORTANT: APEX Images"
log_warn "If APEX images are not loading, copy them manually:"
log_warn "  1. Extract APEX installation zip"
log_warn "  2. Copy images folder: cp -r apex/images/* ${ORDS_HOME}/doc_root/i/"
log_warn "  3. Set permissions: chown -R ${ORDS_USER}:${ORDS_USER} ${ORDS_HOME}/doc_root"
log_info "============================================================"
